import type { Strings } from './strings.ts';

/** French words of L'Aéroport. Only French: no English word is painted on the French scene. */
export const FR: Strings = {
  airport: { welcome: 'Bienvenue à', name: 'Prod-les-Bains' },
  paint: {
    terminal: 'Aérogare',
    tower: 'Contrôle',
    hangar: 'HANGAR 2',
    airline: 'AIR PROD',
    doors: ['SORTIE', 'PORTE 2', 'PORTE 3'],
    pileSign: ['bagages', 'refusés'],
    security: 'CONTRÔLE',
    flag: 'NOUVEAU',
    stamp: 'VALIDÉ',
    pass: 'EMBARQUEMENT',
    placard: 'BIENVENUE',
    cashVan: 'FONDS',
    kaching: 'KLING !',
  },
  signs: {
    roles: { crowd: 'EN CE MOMENT', daily: 'AUJOURD’HUI', total: 'AU TOTAL' },
    deploy: 'MISE EN LIGNE',
    runway: 'PISTE 09',
    build: { idle: 'LIBRE', building: 'EN COURS', ready: 'RÉUSSIE', error: 'RATÉE' },
  },
  board: {
    title: 'Départs',
    runway: 'piste 09',
    columns: ['heure', 'vol', 'statut'],
    runwayState: { free: 'LIBRE', busy: 'OCCUPÉE', closed: 'FERMÉE' },
    unknown: 'NON RECONNU',
    lead: 'NOUVEAU NOUVELLE NOUVEL PREMIER PREMIÈRE UN UNE',
    trail: 'DE DU DES LA LE LES L UN UNE À AU AUX EN SUR PAR DANS POUR SANS ET',
    roles: {
      arrival: 'ARRIVÉE',
      partner: 'PARTENAIRE',
      departure: 'PARTI',
      approval: 'VALIDÉ',
      rejection: 'À REPRENDRE',
      abandon: 'ABANDON',
      like: "J'AIME",
      celebration: 'CAP FRANCHI',
      message: 'MESSAGE',
      publish: 'PUBLIÉ',
      usage: 'UTILISÉ',
      money: 'ENCAISSÉ',
      error: 'ERREUR',
      blocked: 'BLOQUÉ',
    },
  },
  lines: {
    newcomer: ['Bonjour l’équipage !', 'Ravi d’embarquer avec vous.', 'Nouveau à bord, enchanté.'],
    guardStop: ['Contrôle de sécurité. On ne passe pas.', 'Vous ne passerez pas.', 'Ceci reste à la douane.'],
    bot: ['Bip. C’est pas à moi.', 'Bip. Je ne suis pas un robot.', 'Bip. Je repasserai.'],
    guard: ['Livraison pour le coffre.', 'Signez ici, c’est pour vous.', 'Encore un sac pour le coffre.'],
    roger: 'Bien reçu.',
  },
  description: "Une affiche d'aéroport des années 1960 : chaque événement y joue sa petite scène.",
};
