import type { Strings } from './strings.ts';

/** English words of L'Aéroport, written rather than translated. */
export const EN: Strings = {
  airport: { welcome: 'Welcome to', name: 'Prod-on-Sea' },
  paint: {
    terminal: 'Terminal',
    tower: 'Control',
    hangar: 'HANGAR 2',
    airline: 'AIR PROD',
    doors: ['EXIT', 'GATE 2', 'GATE 3'],
    pileSign: ['rejected', 'baggage'],
    security: 'SECURITY',
    flag: 'NEW',
    stamp: 'APPROVED',
    pass: 'BOARDING',
    placard: 'WELCOME',
    cashVan: 'CASH',
    kaching: 'KA-CHING!',
    flight: 'PROD FLIGHT',
    cargoHangar: 'CARGO',
    cargoAirline: 'AIR PROD CARGO',
    station: 'AIRPORT FIRE SERVICE',
    truck: 'FIRE',
  },
  signs: {
    roles: { crowd: 'RIGHT NOW', daily: 'TODAY', total: 'IN TOTAL' },
    deploy: 'DEPLOY',
    runway: 'RUNWAY 09',
    build: { idle: 'CLEAR', building: 'RUNNING', ready: 'SHIPPED', error: 'FAILED' },
  },
  board: {
    title: 'Departures',
    arrivals: 'Arrivals',
    runway: 'runway 09',
    runwayFar: 'runway 27',
    columns: ['time', 'flight', 'status'],
    runwayState: { free: 'CLEAR', busy: 'IN USE', closed: 'CLOSED' },
    unknown: 'UNRECOGNISED',
    lead: 'NEW FIRST A AN',
    trail: 'THE A AN OF ON IN BY TO FOR AT WITH AND',
    roles: {
      arrival: 'ARRIVED',
      partner: 'PARTNER',
      departure: 'GONE',
      approval: 'APPROVED',
      rejection: 'TO REWORK',
      abandon: 'DROPPED',
      like: 'LIKED',
      celebration: 'MILESTONE',
      message: 'MESSAGE',
      publish: 'PUBLISHED',
      usage: 'USED',
      money: 'PAID IN',
      error: 'ERROR',
      blocked: 'BLOCKED',
    },
  },
  lines: {
    newcomer: ['Hello, crew!', 'Glad to be on board.', 'New on board. Nice to meet you.'],
    guardStop: ['Security check. Not today.', 'You shall not pass.', 'That stays with customs.'],
    bot: ['Beep. Not mine.', 'Beep. I am not a robot.', 'Beep. I’ll come back later.'],
    guard: ['Delivery for the vault.', 'Sign here, it’s all yours.', 'Another bag for the vault.'],
    roger: 'Roger.',
    callsign: 'Prod flight',
    clearance: '{callsign}, cleared for take-off, runway 09.',
  },
  jackpot: {
    crew: ['Works on my machine!', 'It’s the cache.', 'Turn it off and on again?', 'Already did.'],
    tower: 'Prod-on-Sea, we have a problem.',
    panel: ['FLIGHT CANCELLED', 'RUNWAY CLOSED'],
  },
  recap: {
    title: 'While you were away',
    hours: { one: '{n} hour', other: '{n} hours' },
    minutes: { one: '{n} minute', other: '{n} minutes' },
    bags: { one: '{n} bag', other: '{n} bags' },
    more: { one: '+ {n} more', other: '+ {n} more' },
    roles: {
      arrival: { one: '{n} arrival', other: '{n} arrivals' },
      partner: { one: '{n} new partner', other: '{n} new partners' },
      departure: { one: '{n} departure', other: '{n} departures' },
      approval: { one: '{n} approval', other: '{n} approvals' },
      rejection: { one: '{n} rejection', other: '{n} rejections' },
      abandon: { one: '{n} drop-out', other: '{n} drop-outs' },
      like: { one: '{n} like', other: '{n} likes' },
      celebration: { one: '{n} milestone', other: '{n} milestones' },
      message: { one: '{n} message', other: '{n} messages' },
      publish: { one: '{n} item published', other: '{n} items published' },
      usage: { one: '{n} use', other: '{n} uses' },
      money: { one: '{n} payment in', other: '{n} payments in' },
      error: { one: '{n} error', other: '{n} errors' },
      blocked: { one: '{n} thing blocked', other: '{n} things blocked' },
      deploy: { one: '{n} deploy', other: '{n} deploys' },
      other: { one: '{n} other event', other: '{n} other events' },
    },
  },
  description: 'A 1960s airport poster: every event plays its own little scene.',
};
