import type { Strings } from './strings.ts';

/** French words of L'Aéroport. Only French: no English word is painted on the French scene. */
export const FR: Strings = {
  airport: { welcome: 'Bienvenue à', name: 'Prod-les-Bains' },
  paint: {
    terminal: 'Aérogare',
    tower: 'Contrôle',
    hangar: 'HANGAR 2',
    airline: 'AIR PROD',
    doors: ['SORTIE', 'PORTE 2', 'PORTE 3'],
    pileSign: ['bagages', 'refusés'],
    security: 'CONTRÔLE',
    flag: 'NOUVEAU',
    stamp: 'VALIDÉ',
    pass: 'EMBARQUEMENT',
    placard: 'BIENVENUE',
    cashVan: 'FONDS',
    kaching: 'KLING !',
    flight: 'VOL PROD',
    cargoHangar: 'FRET',
    cargoAirline: 'AIR PROD FRET',
    station: "POMPIERS DE L'AÉROPORT",
    truck: 'POMPIERS',
  },
  signs: {
    roles: { crowd: 'EN CE MOMENT', daily: 'AUJOURD’HUI', total: 'AU TOTAL' },
    deploy: 'MISE EN LIGNE',
    runway: 'PISTE 09',
    build: { idle: 'LIBRE', building: 'EN COURS', ready: 'RÉUSSIE', error: 'RATÉE' },
  },
  board: {
    title: 'Départs',
    arrivals: 'Arrivées',
    runway: 'piste 09',
    runwayFar: 'piste 27',
    columns: ['heure', 'vol', 'statut'],
    runwayState: { free: 'LIBRE', busy: 'OCCUPÉE', closed: 'FERMÉE' },
    unknown: 'NON RECONNU',
    lead: 'NOUVEAU NOUVELLE NOUVEL PREMIER PREMIÈRE UN UNE',
    trail: 'DE DU DES LA LE LES L UN UNE À AU AUX EN SUR PAR DANS POUR SANS ET',
    roles: {
      arrival: 'ARRIVÉE',
      partner: 'PARTENAIRE',
      departure: 'PARTI',
      approval: 'VALIDÉ',
      rejection: 'À REPRENDRE',
      abandon: 'ABANDON',
      like: "J'AIME",
      celebration: 'CAP FRANCHI',
      message: 'MESSAGE',
      publish: 'PUBLIÉ',
      usage: 'UTILISÉ',
      money: 'ENCAISSÉ',
      error: 'ERREUR',
      blocked: 'BLOQUÉ',
    },
  },
  lines: {
    newcomer: ['Bonjour l’équipage !', 'Ravi d’embarquer avec vous.', 'Nouveau à bord, enchanté.'],
    guardStop: ['Contrôle de sécurité. On ne passe pas.', 'Vous ne passerez pas.', 'Ceci reste à la douane.'],
    bot: ['Bip. C’est pas à moi.', 'Bip. Je ne suis pas un robot.', 'Bip. Je repasserai.'],
    guard: ['Livraison pour le coffre.', 'Signez ici, c’est pour vous.', 'Encore un sac pour le coffre.'],
    roger: 'Bien reçu.',
    callsign: 'Vol Prod',
    clearance: '{callsign}, autorisé au décollage piste 09.',
  },
  jackpot: {
    crew: ['Ça marchait en local !', 'C’est le cache.', 'On redémarre ?', 'C’est déjà fait.'],
    tower: 'Prod-les-Bains, on a un problème.',
    panel: ['VOL ANNULÉ', 'PISTE FERMÉE'],
  },
  recap: {
    title: 'Pendant ton absence',
    hours: { one: '{n} h', other: '{n} h' },
    minutes: { one: '{n} min', other: '{n} min' },
    bags: { one: '{n} bagage', other: '{n} bagages' },
    more: { one: '+ {n} autre', other: '+ {n} autres' },
    roles: {
      arrival: { one: '{n} arrivée', other: '{n} arrivées' },
      partner: { one: '{n} nouveau partenaire', other: '{n} nouveaux partenaires' },
      departure: { one: '{n} départ', other: '{n} départs' },
      approval: { one: '{n} validation', other: '{n} validations' },
      rejection: { one: '{n} refus', other: '{n} refus' },
      abandon: { one: '{n} abandon', other: '{n} abandons' },
      like: { one: '{n} j’aime', other: '{n} j’aime' },
      celebration: { one: '{n} cap franchi', other: '{n} caps franchis' },
      message: { one: '{n} message reçu', other: '{n} messages reçus' },
      publish: { one: '{n} publication', other: '{n} publications' },
      usage: { one: '{n} utilisation', other: '{n} utilisations' },
      money: { one: '{n} encaissement', other: '{n} encaissements' },
      error: { one: '{n} erreur', other: '{n} erreurs' },
      blocked: { one: '{n} blocage', other: '{n} blocages' },
      deploy: { one: '{n} mise en ligne', other: '{n} mises en ligne' },
      other: { one: '{n} autre événement', other: '{n} autres événements' },
    },
  },
  description: "Une affiche d'aéroport des années 1960 : chaque événement y joue sa petite scène.",
};
