import type { Strings } from './strings.ts';

/** English words of L'Aéroport, written rather than translated. */
export const EN: Strings = {
  airport: { welcome: 'Welcome to', name: 'Prod-on-Sea' },
  paint: {
    terminal: 'Terminal',
    tower: 'Control',
    hangar: 'HANGAR 2',
    airline: 'AIR PROD',
    doors: ['EXIT', 'GATE 2', 'GATE 3'],
    pileSign: ['rejected', 'baggage'],
    security: 'SECURITY',
    flag: 'NEW',
    stamp: 'APPROVED',
    pass: 'BOARDING',
    placard: 'WELCOME',
    cashVan: 'CASH',
    kaching: 'KA-CHING!',
  },
  signs: {
    roles: { crowd: 'RIGHT NOW', daily: 'TODAY', total: 'IN TOTAL' },
    deploy: 'DEPLOY',
    runway: 'RUNWAY 09',
    build: { idle: 'CLEAR', building: 'RUNNING', ready: 'SHIPPED', error: 'FAILED' },
  },
  board: {
    title: 'Departures',
    runway: 'runway 09',
    columns: ['time', 'flight', 'status'],
    runwayState: { free: 'CLEAR', busy: 'IN USE', closed: 'CLOSED' },
    unknown: 'UNRECOGNISED',
    lead: 'NEW FIRST A AN',
    trail: 'THE A AN OF ON IN BY TO FOR AT WITH AND',
    roles: {
      arrival: 'ARRIVED',
      partner: 'PARTNER',
      departure: 'GONE',
      approval: 'APPROVED',
      rejection: 'TO REWORK',
      abandon: 'DROPPED',
      like: 'LIKED',
      celebration: 'MILESTONE',
      message: 'MESSAGE',
      publish: 'PUBLISHED',
      usage: 'USED',
      money: 'PAID IN',
      error: 'ERROR',
      blocked: 'BLOCKED',
    },
  },
  lines: {
    newcomer: ['Hello, crew!', 'Glad to be on board.', 'New on board. Nice to meet you.'],
    guardStop: ['Security check. Not today.', 'You shall not pass.', 'That stays with customs.'],
    bot: ['Beep. Not mine.', 'Beep. I am not a robot.', 'Beep. I’ll come back later.'],
    guard: ['Delivery for the vault.', 'Sign here, it’s all yours.', 'Another bag for the vault.'],
    roger: 'Roger.',
  },
  description: 'A 1960s airport poster: every event plays its own little scene.',
};
