import type { SettingsText } from './settings-text.ts';

/** The settings window's words in French. A space before a colon or inside guillemets never breaks. */
export const TEXT_FR: SettingsText = {
  windowTitle: 'Réglages de Deskorama',
  panes: { wallpaper: 'Fond d’écran', sources: 'Sources', try: 'Essayer', webhook: 'Webhook local' },
  back: 'Volet précédent',
  forward: 'Volet suivant',
  reading: (count) => {
    if (count === 0) return 'Aucune Source lue';

    return count === 1 ? '1 Source lue depuis ce Mac' : `${count} Sources lues depuis ce Mac`;
  },

  emptyTitle: 'Branchez un premier service',
  emptyLead:
    'Une Source est un service que Deskorama lit depuis ce Mac, avec votre propre jeton gardé dans le trousseau. Un événement arrive sur le fond d’écran 30 à 90 secondes après avoir eu lieu.',
  emptyScript: 'Un script sur ce Mac plutôt qu’un service\u00a0?',
  emptyScriptLink: 'Utiliser le Webhook local',
  connected: 'Branchées',
  addSource: 'Ajouter une Source',
  connect: (service) => `Brancher\u00a0: ${service}`,
  where: (service, place) => `${service}, ${place}`,
  waiting: 'Première lecture en cours…',
  readAt: (time) => `Lu à ${time}`,
  lastEvent: (what, when) => `Dernier événement\u00a0: ${what}, ${when}`,
  edit: 'Modifier…',
  remove: 'Supprimer',
  more: (name) => `Plus d’actions pour ${name}`,
  fixToken: 'Coller un nouveau jeton',
  fixPermission: 'Corriger le jeton',
  removeTitle: (name) => `Supprimer ${name}\u00a0?`,
  removeBody: 'Son jeton est retiré du trousseau et le fond d’écran ne reçoit plus ses événements.',

  sheetName: 'Nom affiché',
  namePlaceholder: 'Tramlo',
  sheetToken: 'Jeton',
  keepToken: 'Vide pour garder le jeton actuel',
  sheetCreate: 'Créer le jeton',
  sheetOpen: (site) => `Ouvrir ${site}`,
  sheetTick: 'Cocher ces permissions, en lecture seule',
  sheetPaste: 'Coller le jeton',
  sheetKeychain: 'Gardé dans le trousseau macOS.',
  sheetEvery: 'Lire toutes les',
  seconds: 's',
  sheetBounds: (min, max) => `de ${min} à ${max}`,
  sheetTestTitle: 'Test',
  sheetTest: 'Tester',
  sheetRetest: 'Tester à nouveau',
  sheetTesting: 'Test en cours…',
  sheetFound: (where, count) =>
    count === 1
      ? `${where} a répondu, voici son dernier événement.`
      : `${where} a répondu, voici ses ${count} derniers événements.`,
  sheetCounts: (where) => `${where} a répondu, voici ce qu’il compte.`,
  sheetNoEvent: (where) => `${where} a répondu, aucun événement pour l’instant.`,
  sheetPlaysAs: (time, role) => `${time}, joue comme ${role}`,
  sheetNothingSaved: 'Rien n’est enregistré avant Enregistrer.',
  sheetFix: 'Corrigez les champs en rouge.',
  sheetFailed: 'Ça n’a pas marché\u00a0: réessayez.',
  cancel: 'Annuler',
  save: 'Enregistrer',

  themes: 'Thème',
  themeNow: 'Sur votre bureau',
  dayNight: 'Le jour et la nuit suivent l’heure du Mac.',
  day: 'Jour',
  night: 'Nuit',
  general: 'Général',
  language: 'Langue',
  macLanguage: (name) => `Celle du Mac (${name})`,
  openAtLogin: 'Ouvrir Deskorama à l’ouverture de session',
  needsApproval: 'macOS attend votre accord dans Réglages Système › Général › Ouverture.',
  scene: 'La scène',
  sceneNote:
    'Avec plusieurs Sources, choisissez celle qui donne son nom à la scène et celle qui nourrit chaque compteur.',
  brand: 'Nom sur la scène',
  gaugeNames: {
    crowd: 'Compteur «\u00a0en ce moment\u00a0»',
    daily: 'Compteur «\u00a0aujourd’hui\u00a0»',
    total: 'Compteur «\u00a0au total\u00a0»',
  },
  sameAsScene: (name) => `Comme la scène (${name})`,

  tryLead: 'Chaque bouton joue un faux événement sur le fond d’écran, sans attendre un vrai.',
  playsOn: 'Joue sur',
  play: (name) => `Jouer\u00a0: ${name}`,
  played: (name, theme) => `Joué sur ${theme}\u00a0: ${name}.`,
  rare: 'rare',
  jackpotLead: 'Le grand moment de la scène\u00a0: il ne joue que pour une vraie mise en ligne ratée, ou d’ici.',
  roleGroups: {
    people: 'Des gens',
    work: 'Le travail jugé',
    reactions: 'Les réactions',
    money: 'L’argent et les intrus',
    shipping: 'La production',
  },

  webhookOn: 'Activer le Webhook local',
  portTaken: (address) => `${address} est déjà pris par une autre app\u00a0: le Webhook local n’écoute pas.`,
  access: 'Accès pour vos scripts',
  address: 'Adresse',
  secret: 'Secret',
  show: 'Afficher le secret',
  hide: 'Masquer le secret',
  copy: 'Copier',
  regenerate: 'Régénérer…',
  regenerateTitle: 'Régénérer le secret\u00a0?',
  regenerateBody: 'Les scripts qui envoient l’ancien secret seront refusés tant qu’ils n’ont pas le nouveau.',
  regenerateConfirm: 'Régénérer',
  regenerateFailed: 'Le secret n’a pas été régénéré : l’ancien fonctionne toujours.',
  example: 'Essayer depuis le Terminal',
  exampleNote: 'Le corps suit le format JSON documenté. La copie met le vrai secret à la place de $DESKORAMA_SECRET.',
  received: 'Derniers événements reçus',
  noneReceived: 'Aucun événement reçu depuis l’ouverture de Deskorama.',
};
