import type { SettingsText } from './settings-text.ts';

/** The settings window's words in English. */
export const TEXT_EN: SettingsText = {
  windowTitle: 'Deskorama Settings',
  panes: { wallpaper: 'Wallpaper', sources: 'Sources', try: 'Try it', webhook: 'Local webhook' },
  back: 'Previous pane',
  forward: 'Next pane',
  reading: (count) => {
    if (count === 0) return 'No Source read';

    return count === 1 ? '1 Source read from this Mac' : `${count} Sources read from this Mac`;
  },

  emptyTitle: 'Connect a first service',
  emptyLead:
    'A Source is a service Deskorama reads from this Mac, with your own token kept in the Keychain. An Event reaches the wallpaper 30 to 90 seconds after it happens.',
  emptyScript: 'A script on this Mac rather than a service?',
  emptyScriptLink: 'Use the Local webhook',
  connected: 'Connected',
  addSource: 'Add a Source',
  connect: (service) => `Connect: ${service}`,
  where: (service, place) => `${service}, ${place}`,
  waiting: 'Reading it for the first time…',
  readAt: (time) => `Read at ${time}`,
  lastEvent: (what, when) => `Last Event: ${what}, ${when}`,
  edit: 'Edit…',
  remove: 'Remove',
  more: (name) => `More actions for ${name}`,
  fixToken: 'Paste a new token',
  fixPermission: 'Fix the token',
  removeTitle: (name) => `Remove ${name}?`,
  removeBody: 'Its token is removed from the Keychain and the wallpaper stops receiving its Events.',

  sheetName: 'Display name',
  namePlaceholder: 'Tramlo',
  sheetToken: 'Token',
  keepToken: 'Empty to keep the current token',
  sheetCreate: 'Create the token',
  sheetOpen: (site) => `Open ${site}`,
  sheetTick: 'Tick these permissions, read-only',
  sheetPaste: 'Paste the token',
  sheetKeychain: 'Kept in the macOS Keychain.',
  sheetEvery: 'Read every',
  seconds: 's',
  sheetBounds: (min, max) => `${min} to ${max}`,
  sheetTestTitle: 'Test',
  sheetTest: 'Test',
  sheetRetest: 'Test again',
  sheetTesting: 'Testing…',
  sheetFound: (where, count) =>
    count === 1
      ? `${where} answered, here is its latest Event.`
      : `${where} answered, here are its ${count} latest Events.`,
  sheetCounts: (where) => `${where} answered, here is what it counts.`,
  sheetNoEvent: (where) => `${where} answered, no Event yet.`,
  sheetPlaysAs: (time, role) => `${time}, plays as ${role}`,
  sheetNothingSaved: 'Nothing is saved before Save.',
  sheetFix: 'Fix the fields in red.',
  sheetFailed: 'That did not work: try again.',
  cancel: 'Cancel',
  save: 'Save',

  themes: 'Theme',
  themeNow: 'On your desktop',
  dayNight: 'Day and night follow the Mac’s clock.',
  day: 'Day',
  night: 'Night',
  general: 'General',
  language: 'Language',
  macLanguage: (name) => `The Mac’s own (${name})`,
  openAtLogin: 'Open Deskorama at login',
  needsApproval: 'macOS waits for your approval in System Settings › General › Login Items.',
  scene: 'The scene',
  sceneNote: 'With several Sources, choose the one that names the scene and the one that feeds each Gauge.',
  brand: 'Name on the scene',
  gaugeNames: { crowd: '“Right now” Gauge', daily: '“Today” Gauge', total: '“In total” Gauge' },
  sameAsScene: (name) => `Same as the scene (${name})`,

  tryLead: 'Each button plays a fake Event on the wallpaper, without waiting for a real one.',
  playsOn: 'Plays on',
  play: (name) => `Play: ${name}`,
  played: (name, theme) => `Played on ${theme}: ${name}.`,
  rare: 'rare',
  jackpotLead: 'The scene’s big moment: it only plays for a real failed deploy, or from here.',
  roleGroups: {
    people: 'People',
    work: 'Work judged',
    reactions: 'Reactions',
    money: 'Money and intruders',
    shipping: 'Shipping',
  },

  webhookOn: 'Turn on the Local webhook',
  portTaken: (address) => `${address} is taken by another app: the Local webhook is not listening.`,
  access: 'Access for your scripts',
  address: 'Address',
  secret: 'Secret',
  show: 'Show the secret',
  hide: 'Hide the secret',
  copy: 'Copy',
  regenerate: 'Regenerate…',
  regenerateTitle: 'Regenerate the secret?',
  regenerateBody: 'Scripts that send the old secret are turned away until they have the new one.',
  regenerateConfirm: 'Regenerate',
  regenerateFailed: 'The secret was not regenerated: the old one still works.',
  example: 'Try it from Terminal',
  exampleNote:
    'The body follows the documented JSON format. Copying puts the real secret in place of $DESKORAMA_SECRET.',
  received: 'Latest Events received',
  noneReceived: 'No Event received since Deskorama opened.',
};
