import type { Strings } from './strings.ts';

/** L'Immeuble in French. */
export const FR: Strings = {
  sounds: {
    arrival: 'TOC TOC !',
    partner: 'TADAM !',
    departure: null,
    approval: 'PAF !',
    rejection: 'BOF !',
    abandon: 'HOP !',
    like: null,
    celebration: 'WAOUH !',
    message: null,
    publish: null,
    usage: null,
    money: 'KA-CHING !',
    error: 'BIP !',
    blocked: 'HALTE !',
    deploy: null,
    other: null,
  },
  errors: ['BIP !', 'BZZT !', 'AÏE !'],
  props: { via: 'VIA', stop: 'STOP', ok: 'VU', plusOne: '+1' },
  board: { title: 'SUR {brand}' },
  site: {
    days: ['JOUR SANS', 'JOURS SANS'],
    what: 'ACCIDENT',
    idle: 'DE MISE EN LIGNE',
    building: 'MISE EN LIGNE',
    live: 'EN LIGNE À {time}',
  },
  hall: ['INTRUS', 'BLOQUÉS'],
  arcade: { title: 'FIN DE PARTIE', ask: 'CONTINUER ? {n}', end: 'À LA PROCHAINE', coin: 'INSÉREZ UNE PIÈCE' },
  concierge: { sigh: 'PFF', line: ["ET C'EST MOI", 'QUI BALAIE.'] },
  collapse: { crack: 'CRAC !', help: 'AU SECOURS !' },
  recap: {
    title: 'PENDANT TON ABSENCE',
    nouns: {
      arrival: ['ARRIVÉE', 'ARRIVÉES'],
      partner: ['RECRUE DE MARQUE', 'RECRUES DE MARQUE'],
      departure: ['DÉPART', 'DÉPARTS'],
      approval: ['VALIDATION', 'VALIDATIONS'],
      rejection: ['REFUS', 'REFUS'],
      abandon: ['ABANDON', 'ABANDONS'],
      like: ["J'AIME", "J'AIME"],
      celebration: ['GRAND MOMENT', 'GRANDS MOMENTS'],
      message: ['MESSAGE', 'MESSAGES'],
      publish: ['PUBLICATION', 'PUBLICATIONS'],
      usage: ['UTILISATION', 'UTILISATIONS'],
      money: ["RENTRÉE D'ARGENT", "RENTRÉES D'ARGENT"],
      error: ['ERREUR', 'ERREURS'],
      blocked: ['INTRUS BLOQUÉ', 'INTRUS BLOQUÉS'],
      deploy: ['MISE EN LIGNE', 'MISES EN LIGNE'],
      other: ['ÉVÉNEMENT', 'ÉVÉNEMENTS'],
    },
    more: ['AUTRE', 'AUTRES'],
  },
  description:
    'Un immeuble parisien en coupe : les appartements allumés, la loge, la grue sur le toit et la rue. Chaque événement y joue une petite scène avec sa légende.',
};
