import type { Strings } from './strings.ts';

/** L'Immeuble in English: native lines, not translations. */
export const EN: Strings = {
  sounds: {
    arrival: 'KNOCK KNOCK!',
    partner: 'TA-DA!',
    departure: null,
    approval: 'THUD!',
    rejection: 'NAH!',
    abandon: 'TOSS!',
    like: null,
    celebration: 'WOW!',
    message: null,
    publish: null,
    usage: null,
    money: 'KA-CHING!',
    error: 'BEEP!',
    blocked: 'HALT!',
    deploy: null,
    other: null,
  },
  errors: ['BEEP!', 'BZZT!', 'OUCH!'],
  props: { via: 'VIA', stop: 'STOP', ok: 'OK', plusOne: '+1' },
  board: { title: 'ON {brand}' },
  site: {
    days: ['DAY SINCE', 'DAYS SINCE'],
    what: 'LAST CRASH',
    idle: 'IN PROD',
    building: 'DEPLOYING',
    live: 'LIVE AT {time}',
  },
  hall: ['KEPT', 'OUT'],
  arcade: { title: 'GAME OVER', ask: 'CONTINUE? {n}', end: 'SEE YOU SOON', coin: 'INSERT COIN' },
  concierge: { sigh: 'UGH', line: ["I'LL GET", 'THE MOP.'] },
  collapse: { crack: 'CRACK!', help: 'HELP!' },
  recap: {
    title: 'WHILE YOU WERE AWAY',
    nouns: {
      arrival: ['ARRIVAL', 'ARRIVALS'],
      partner: ['BIG ARRIVAL', 'BIG ARRIVALS'],
      departure: ['DEPARTURE', 'DEPARTURES'],
      approval: ['APPROVAL', 'APPROVALS'],
      rejection: ['TURN-DOWN', 'TURN-DOWNS'],
      abandon: ['DROP-OUT', 'DROP-OUTS'],
      like: ['LIKE', 'LIKES'],
      celebration: ['BIG MOMENT', 'BIG MOMENTS'],
      message: ['MESSAGE', 'MESSAGES'],
      publish: ['RELEASE', 'RELEASES'],
      usage: ['USE', 'USES'],
      money: ['PAYMENT', 'PAYMENTS'],
      error: ['ERROR', 'ERRORS'],
      blocked: ['INTRUDER KEPT OUT', 'INTRUDERS KEPT OUT'],
      deploy: ['DEPLOY', 'DEPLOYS'],
      other: ['EVENT', 'EVENTS'],
    },
    more: ['MORE', 'MORE'],
  },
  description:
    'A Paris apartment building cut open: the lit flats, the concierge’s lodge, the crane on the roof and the street. Every event plays a small scene there with its caption.',
};
